# wpa_supplicant configuration
ctrl_interface=/data/vendor/wifi/wpa/sockets
update_config=1
device_name=A210_EVB
manufacturer=Alibaba
model_name=Zhihe A210 EVB
model_number=A210
serial_number=0
device_type=10-0050F204-5
config_methods=physical_display virtual_push_button
p2p_disabled=1
external_sim=0
